In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
%autosave 20

Autosaving every 20 seconds


In [2]:
import torch 
import  torch.nn as nn
import torch.functional as F
from torchvision import transforms

In [3]:
torch.cuda.is_available()

True

In [5]:
!nvidia-smi

Wed Dec 28 15:14:22 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   59C    P5    20W /  N/A |     77MiB / 16384MiB |     21%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
import numpy as np

In [8]:
v0 = np.array(1.3)
v1 = np.array([1.,2.,3.,4.])
v2 = np.array([[1.,2.],[3.,4.]])

In [14]:
v0
v1
v2
print(v0.ndim)
print(v1.ndim)
print(v2.ndim)

array(1.3)

array([1., 2., 3., 4.])

array([[1., 2.],
       [3., 4.]])

0
1
2


In [19]:
numpy_array = np.array([1,2,3])
numpy_array.dtype

dtype('int64')

###  First method from numpy to Torch

In [23]:
t1 = torch.Tensor(numpy_array,)
#It is a constructure - same as torch.FloatTensor
#Use  by default as float32
#All other tensors inherit from this main tensor class

In [25]:
t1
type(t1)
t1.dtype                                                                                                                                                                                                                                                       

tensor([1., 2., 3.])

torch.Tensor

torch.float32

In [32]:
t1.cuda()
t1.cpu()

tensor([1., 2., 3.], device='cuda:0')

tensor([1., 2., 3.])

### Second Method

In [33]:
t2 = torch.tensor(numpy_array)
#Factory function (create a New Tensor from numpy array )
#Doesn't share underlying memory with numpy
#Always copy the data
torch.tensor(numpy_array,
         dtype=None, device=None, requires_grad=False, pin_memory=False)

#Highly Recommended to Use as it can go to GPU , and Numpy can't

tensor([1, 2, 3])

In [34]:
t2
type(t2)
t2.dtype                                                                                                                                                                                                                                                       

tensor([1, 2, 3])

torch.Tensor

torch.int64

### Third Method  

In [38]:
t3 = torch.as_tensor(numpy_array)
#Factory Function 
#Going to produce a New tensor of the same type
#Shares underline memory with Numpy array( Changing  ojne will change other)
#Can Accepy any python Data stracture, It can be Dictionary, List etc

In [36]:
t3
type(t3)
t3.dtype

tensor([1, 2, 3])

torch.Tensor

torch.int64

### Fourth method

In [41]:
t4 = torch.from_numpy(numpy_array)
#Can only Accept only Numpy

In [42]:
t4
type(t4)
t4.dtype

tensor([1, 2, 3])

torch.Tensor

torch.int64

In [44]:
numpy_array
numpy_array *= 4
numpy_array

array([1, 2, 3])

array([ 4,  8, 12])

In [46]:
t1
t2
t3 #underlined memory changed 
t4 #underlined memory changed 

tensor([1., 2., 3.])

tensor([1, 2, 3])

tensor([ 4,  8, 12])

tensor([ 4,  8, 12])

In [49]:
t1
t1*=2

tensor([1., 2., 3.])

In [50]:
t1
t2
t3 #underlined memory changed 
t4 #underlined memory changed 

tensor([2., 4., 6.])

tensor([1, 2, 3])

tensor([ 4,  8, 12])

tensor([ 4,  8, 12])

In [52]:
t5 = t4.cuda()
t4
t5

tensor([ 4,  8, 12])

tensor([ 4,  8, 12], device='cuda:0')

In [53]:
t4+t5

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

###  some important function to know in Torch

In [55]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [56]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [57]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [59]:
torch.rand(3,4)

tensor([[0.6275, 0.6828, 0.1490, 0.7700],
        [0.7153, 0.7327, 0.6402, 0.1602],
        [0.9670, 0.6015, 0.0307, 0.8723]])

In [61]:
data = torch.tensor(torch.rand(2,3))

/tmp/ipykernel_6363/3996130508.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data = torch.tensor(torch.rand(2,3))


In [62]:
data

tensor([[0.5440, 0.7317, 0.8392],
        [0.4421, 0.4625, 0.2335]])

In [65]:
data[0:1]
data[:,1]
data[:,0:2  ]

tensor([[0.5440, 0.7317, 0.8392]])

tensor([0.7317, 0.4625])

tensor([[0.5440, 0.7317],
        [0.4421, 0.4625]])

### Autograd

In [66]:
# Automatic Differentation for all the operations on Tensors 
# The backward grapg is automatically defined by the forward graph!

In [67]:
from torch.autograd import grad

In [72]:
x1 = torch.tensor(2,requires_grad = True,dtype = torch.float16)
x2 = torch.tensor(3,requires_grad = True,dtype = torch.float16)
x3 = torch.tensor(1,requires_grad = True,dtype = torch.float16)
x4 = torch.tensor(4,requires_grad = True,dtype = torch.float16)

In [74]:
x1
x2
x3
x4

tensor(2., dtype=torch.float16, requires_grad=True)

tensor(3., dtype=torch.float16, requires_grad=True)

tensor(1., dtype=torch.float16, requires_grad=True)

tensor(4., dtype=torch.float16, requires_grad=True)

In [79]:
z1= x1*x2

z2 = x3*x4

f = z1+z2

In [83]:
z1
z2
f

tensor(6., dtype=torch.float16, grad_fn=<MulBackward0>)

tensor(4., dtype=torch.float16, grad_fn=<MulBackward0>)

tensor(10., dtype=torch.float16, grad_fn=<AddBackward0>)

In [84]:
df_dx = grad(outputs=f,inputs=[x1,x2,x3,x4])

In [85]:
x1,x2,x3,x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True))

In [87]:
import torch.nn.functional as F
from torch.optim import SGD

In [97]:
optim = SGD(params=[x1,x2,x3,x4],lr = 2)

In [98]:
optim.zero_grad()

In [99]:
z1= x1*x2

z2 = x3*x4

f = z1+z2

In [100]:
f.backward()

In [101]:
x1,x2,x3,x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True))

In [102]:
optim.zero_grad()

In [103]:
x1,x2,x3,x4

(tensor(2., dtype=torch.float16, requires_grad=True),
 tensor(3., dtype=torch.float16, requires_grad=True),
 tensor(1., dtype=torch.float16, requires_grad=True),
 tensor(4., dtype=torch.float16, requires_grad=True))

### Operations

In [104]:
t = torch.tensor(torch.rand(3,4))

/tmp/ipykernel_6363/3185064091.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t = torch.tensor(torch.rand(3,4))


In [107]:
t.shape,t.size(),len(t)

(torch.Size([3, 4]), torch.Size([3, 4]), 3)

In [108]:
torch.tensor(t.shape).prod()

tensor(12)

In [109]:
t.numel()

12

In [116]:
t.reshape(1,12)

tensor([[0.1415, 0.0563, 0.7497, 0.7336, 0.8272, 0.8458, 0.9410, 0.9289, 0.8436,
         0.9972, 0.3896, 0.1428]])

In [115]:
t.reshape(12,1)

tensor([[0.1415],
        [0.0563],
        [0.7497],
        [0.7336],
        [0.8272],
        [0.8458],
        [0.9410],
        [0.9289],
        [0.8436],
        [0.9972],
        [0.3896],
        [0.1428]])